[config]
port = 8504

[servers.alpha]
enabled = true
url = "https://editor.wallboard.us/displayer/index.html#/87ba0422c82d4fd280925e31ac1709ac/Default?signageModeSecret=35b3cc6795534c488b2335c89ce25891"

[servers.bravo]
enabled = true
url = "https://matrix.tty4.dev"

[servers.charlie]
enabled = false
url = "https://google.com"