#!/bin/bash
[ -z "$chrome" ] && chrome="chromium"
pids=
destinations=

_end() {
    reset
    kill $pids 2> /dev/null
    [[ -z $1 ]] && echo -e "\e[31mShutting down Koala...\e[0m" && exit 0
    [[ $1 == 1 ]] && echo -e "\e[31m$2 is missing required values.\e[0m" && exit 1
    [[ $1 == 2 ]] && echo -e "\e[31m$2 contains a duplicate destination.\e[0m" && exit 2
    exit 127
}

trap _end INT

create_stream() {
    local DISPLAY=:`shuf -i 99-999999999 -n1`
    local width=1920
    local height=1080
    local colordepth=24
    local framerate=30
    local bitrate=6000

    # parse config
    while read line; do
        # skip empty lines
        [ -z "$line" ] && continue
        # ignore comments
        [[ $line == \#* ]] && continue
        local "$line"
    done < "$1"

    [[ -z "$name" || -z "$webpage" || -z "$webpage" ]] && _end 1 $1

    for i in $destinations; do
        [ $i == $destination ] && _end 2 $1
    done

    destinations="$destinations $destination"

    Xvfb ${DISPLAY} -screen 0 ${width}x${height}x${colordepth} &
    pids="$! $pids"

    DISPLAY=$DISPLAY ${chrome} \
        --user-data-dir=$(mktemp -d) \
        --kiosk \
        --fullscreen \
        --window-position=0,0 \
        --window-size=${width},${height} \
        ${webpage} 2> /dev/null &
    pids="$! $pids"

    ffmpeg \
        -video_size ${width}x${height} \
        -y \
        -r ${framerate} \
        -f x11grab \
        -draw_mouse 0 \
        -s ${width}x${height} \
        -i ${DISPLAY} \
        -b:v ${bitrate}k \
        -f mpegts \
        udp://${destination} 2> /dev/null &
    pids="$! $pids"

    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}\e[0m @ \e[33m${width}x${height}x${colordepth}\e[0m"
    echo -e "URL: \e[32m${webpage}\e[0m"
}

for stream in streams/*; do
    create_stream "$stream"
done

wait $@
