#!/bin/bash
[ -z "$chrome" ] && chrome="chromium"

pid_array=()
destination_array=()
out="/dev/null"

# get options
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -v | --verbose )
    out="/dev/stdout"
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

_end() {
    kill "${pid_array[@]}" 2> $out
    [[ -z $1 ]] && echo -e "\e[31mShutting down Koala...\e[0m" && exit 0
    [[ $1 == 1 ]] && echo -e "\e[31m$2 is missing required value: $3\e[0m" && exit 1
    [[ $1 == 2 ]] && echo -e "\e[31m$2 contains a duplicate destination.\e[0m" && exit 2
    exit 127
}

trap _end INT

newline_check() {
    [[ $(tail -c1 "$1" | wc -l) -gt 0 ]]
}

create_stream() {
    local Xdisplay=1000
    while [ -f /tmp/.X${Xdisplay}-lock ]; do
        ((Xdisplay+=1))
    done
    local width=1920
    local height=1080
    local colordepth=24
    local framerate=30
    local bitrate=6000

    # parse config
    while read line; do
        # skip empty lines
        [ -z "$line" ] && continue
        # ignore comments
        [[ $line == \#* ]] && continue
        local "$line"
    done < "$1"

    [[ -z "$name" ]] && _end 1 $1 name
    [[ -z "$webpage" ]] && _end 1 $1 webpage
    [[ -z "$destination" ]] && _end 1 $1 destination

    # check for duplicate destinations
    for i in ${destination_array[@]}; do
        [ $i == $destination ] && _end 2 $1
    done

    destination_array+=($destination)

    Xvfb :${Xdisplay} -screen 0 ${width}x${height}x${colordepth} &
    pid_array+=($!)
    until [ -f /tmp/.X${Xdisplay}-lock ]; do
            sleep .01s
    done

    DISPLAY=:$Xdisplay ${chrome} \
        --user-data-dir=$(mktemp -d) \
        --kiosk \
        --fullscreen \
        --window-position=0,0 \
        --window-size=${width},${height} \
        ${webpage} 2> $out &
    pid_array+=($!)

    ffmpeg \
        -video_size ${width}x${height} \
        -y \
        -r ${framerate} \
        -f x11grab \
        -draw_mouse 0 \
        -s ${width}x${height} \
        -i :${Xdisplay} \
        -b:v ${bitrate}k \
        -f mpegts \
        udp://${destination} 2> $out &
    pid_array+=($!)

    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}\e[0m @ \e[33m${width}x${height}x${colordepth}\e[0m (:${Xdisplay})"
    echo -e "URL: \e[32m${webpage}\e[0m"
}

for stream in streams/*; do
    if ! newline_check "$stream"; then
        echo "" >> "$stream"
    fi
    create_stream "$stream"
done

wait $@
