#!/bin/bash

# If everything is working correctly, this script shouldn't output anything.
# Note: this script parses `ps` for some assertions and may misbehave on
#       some systems

set -o pipefail
koala_dir=$PWD

koala_no_color() {
  ${koala_dir}/koala | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g'
}

assert() {
  if [[ $1 != $2 ]]; then
    echo Assertion failed at line `caller`
    echo Expected:
    echo $1
    echo Got:
    echo $2
  fi
}

assert_koala() {
  local output=$(koala_no_color)
  if [[ "$output" != "$@" ]]; then
    echo Assertion failed at line `caller`
    echo Expected:
    echo "$@"
    echo Got:
    echo $output
  fi
}

# test for missing name
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
webpage=https://google.com
destination=127.0.0.1:1337
EOF
assert_koala "streams/test-stream is missing required value: name"

# test for missing webpage
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
destination=127.0.0.1:1337
EOF
assert_koala "streams/test-stream is missing required value: webpage"

# test for missing destination
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
webpage=https://google.com
EOF
assert_koala "streams/test-stream is missing required value: destination"

# test for duplicate destinations
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
webpage=https://google.com
destination=127.0.0.1:1337
EOF
cat << EOF > streams/test-stream2
name=test2
webpage=https://google.com
destination=127.0.0.1:1337
EOF
koala_no_color > /dev/null
assert $? 2

# test that all processes are exited when shutting down
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
webpage=https://google.com
destination=127.0.0.1:1337
EOF
cat << EOF > streams/test-stream2
name=test2
webpage=https://google.com
destination=127.0.0.1:1338
EOF
koala_no_color > /dev/null &
sleep 3s
ps axf | grep ${koala_dir}/koala | grep -v grep | awk '{print "kill -2 " $1}' | sh
sleep 3s
ps -x | grep -A1 -P '^(?!.*grep).*Xvfb'
assert 1 $?
ps -x | grep -A1 -P '^(?!.*grep).*kiosk'
assert 1 $?
ps -x | grep -A1 -P '^(?!.*grep).*ffmpeg'
assert 1 $?
