#!/bin/bash

# If everything is working correctly, this script shouldn't output anything
# after about 20 seconds.
#
# Note: this script parses `ps` for some assertions and may misbehave on
#       some systems

set -o pipefail
koala=${PWD}/koala

strip_color() {
  sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g'
}

assert() {
  if [[ $1 != $2 ]]; then
    echo "Assertion failed at line `caller`"
    echo "Expected:"
    echo -e "\e[32m$1\e[0m"
    echo "Got:"
    echo -e "\e[31m$2\e[0m"
    exit 1
  fi
}

assert_koala() {
  local output=$($koala | strip_color)
  if [[ "$output" != "$@" ]]; then
    echo "Assertion failed at line `caller`"
    echo "Expected:"
    echo -e "\e[32m$@\e[0m"
    echo "Got:"
    echo -e "\e[31m$output\e[0m"
    exit 2
  fi
}

# test for missing stream directory
cd `mktemp -d`
assert_koala "Could not find stream directory '${PWD}/streams'."

# test for empty stream directory
cd `mktemp -d` && mkdir streams
assert_koala "Stream directory '${PWD}/streams' is empty."

# test for missing name
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
url=https://google.com
destination=127.0.0.1:1337
EOF
assert_koala "'${PWD}/streams/test-stream' is missing required value: name"

# test for missing url (directory-mode)
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
destination=127.0.0.1:1337
EOF
$koala | strip_color > /dev/null
assert 1 $?

# test for missing destination (directory-mode)
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
url=https://google.com
EOF
$koala | strip_color > /dev/null
assert 1 $?

# test for missing url (oneshot-mode)
cd `mktemp -d`
$koala -o -d 127.0.0.1:1337 | strip_color > /dev/null
assert 1 $?

# test for missing destination (oneshot-mode)
$koala -o -u https://google.com | strip_color > /dev/null
assert 1 $?

# test for duplicate destinations
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
url=https://google.com
destination=127.0.0.1:1337
EOF
cat << EOF > streams/test-stream2
name=test2
url=https://google.com
destination=127.0.0.1:1337
EOF
$koala | strip_color > /dev/null
assert 2 $?

# test file mode
set -e
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
url=https://google.com
destination=127.0.0.1:1337
EOF
$koala -f streams/test-stream | strip_color > /dev/null &
sleep 3s
kill $(jobs -p)
sleep 3s
set +e

# test oneshot mode
set -e
cd `mktemp -d`
$koala -o -u https://google.com -d 127.0.0.1:1337 | strip_color > /dev/null &
sleep 3s
kill $(jobs -p)
sleep 3s
set +e

# test that all processes are exited when shutting down
set -e
cd `mktemp -d` && mkdir streams
cat << EOF > streams/test-stream
name=test
url=https://google.com
destination=127.0.0.1:1337
EOF
cat << EOF > streams/test-stream2
name=test2
url=https://google.com
destination=127.0.0.1:1338
EOF
$koala | strip_color > /dev/null &
sleep 3s
kill $(jobs -p)
sleep 3s
set +e
ps x | grep -v grep | grep Xvfb
assert 1 $?
ps x | grep -v grep | grep kiosk
assert 1 $?
ps x | grep -v grep | grep ffmpeg
assert 1 $?
